dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

branches:
  only:
    - develop
    - main

notifications:
  email: false

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm ci

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/lionel-app
  on:
    branch: main
